### create tenant
POST http://localhost:4000/tenants
Content-Type: application/json

{
  "name": "PSL",
  "slug": "Sports-league"
}

### get tenant
GET http://localhost:4000/tenants

### Delete the tenant
DELETE http://localhost:4000/tenants/98905008-4e6f-40fd-9cf1-23c2a3e2a626