### create tenant
POST http://localhost:4000/tenants
Content-Type: application/json

{
  "name": "PSL",
  "slug": "Sports-league"
}

### get tenant
GET http://localhost:4000/tenants

### Delete the tenant
DELETE http://localhost:4000/tenants/e02533a4-f91a-4038-bb8b-f7eae43f80b2